version: 10.0.0-{build}

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\cargo-update

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  # https://www.msys2.org/news/#2020-05-17-32-bit-msys2-no-longer-actively-supported
  - curl -SL http://repo.msys2.org/msys/x86_64/msys2-keyring-1~20201002-1-any.pkg.tar.xz -oC:\msys2-keyring.txz
  - curl -SL http://repo.msys2.org/msys/x86_64/msys2-keyring-1~20220623-1-any.pkg.tar.zst -oC:\msys2-keyring.tzst
  - curl -SL http://repo.msys2.org/msys/x86_64/zstd-1.4.7-1-x86_64.pkg.tar.xz -oC:\zstd.txz
  - curl -SL http://repo.msys2.org/msys/x86_64/pacman-5.2.2-5-x86_64.pkg.tar.xz -oC:\pacman.txz
  - pacman --noconfirm -U C:\msys2-keyring.txz
  - pacman --noconfirm -U C:\zstd.txz
  - pacman --noconfirm -U C:\pacman.txz
  - pacman --noconfirm -U C:\msys2-keyring.tzst
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy pacman"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -Su"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain zip"
  -
  - mkdir target\release\deps
  - cp C:\Windows\System32\ntdll.dll target\release\deps
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"

build: off
build_script:
  - cargo build --verbose --release
  -
  - mkdir cargo-update-v10.0.0
  - cp target\release\cargo-install-update.exe target\release\cargo-install-update-config.exe cargo-update-v10.0.0\
  - strip --strip-all --remove-section=.comment --remove-section=.note cargo-update-v10.0.0/cargo-install-update.exe cargo-update-v10.0.0/cargo-install-update-config.exe
  - zip -9r cargo-update-v10.0.0.zip cargo-update-v10.0.0

test: off
test_script:
  - cargo test --verbose --release

artifacts:
  - path: cargo-update-v10.0.0.zip

deploy:
  provider: GitHub
  artifact: cargo-update-v10.0.0.zip
  auth_token:
    secure: FNqRpbXgjNh7VrtHCIGadt7Pwv9HGq4kyUCQFueRLJvQCCWWWgko3PwiZvYlaAEG
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
