[package]
name = "cargo-update"
description = "A cargo subcommand for checking and applying updates to installed executables"
documentation = "https://cdn.rawgit.com/nabijaczleweli/cargo-update/doc/cargo_update/index.html"
repository = "https://github.com/nabijaczleweli/cargo-update"
readme = "README.md"
keywords = ["cargo", "update", "plugin", "subcommand"]
license = "MIT"
# Remember to also update in appveyor.yml
version = "0.1.0"
# Remember to also update in cargo-update.md
authors = ["nabijaczleweli <nabijaczleweli@gmail.com>"]
exclude = ["*.enc"]


[dependencies]
lazy_static = "0.2"
array_tool = "0.3"
tabwriter = "0.1"
semver = "0.5"
hyper = "0.9"
regex = "0.1"
clap = "2.16"
json = "0.10"
toml = "0.2"


[[bin]]
name = "cargo-install-update"
test = false
doc = false
