[package]
name = "cargo-update"
description = "A cargo subcommand for checking and applying updates to installed executables"
documentation = "https://cdn.rawgit.com/nabijaczleweli/cargo-update/doc/cargo_update/index.html"
repository = "https://github.com/nabijaczleweli/cargo-update"
readme = "README.md"
keywords = ["cargo", "update", "plugin", "subcommand"]
categories = ["development-tools::cargo-plugins"]
license = "MIT"
build = "build.rs"
# Remember to also update in appveyor.yml
version = "0.7.1"
# Remember to also update in cargo-install-update.md
authors = ["nabijaczleweli <nabijaczleweli@gmail.com>",
           "Yann Simon <yann.simon.fr@gmail.com>",
           "ven <vendethiel@hotmail.fr>",
           "Cat Plus Plus <piotrlegnica@piotrl.pl>",
           "Liigo <liigo@qq.com>",
           "azyobuzin <azyobuzin@users.sourceforge.jp>"]
exclude = ["*.enc"]


[dependencies]
lazy_static = "0.2"
array_tool = "0.3"
tabwriter = "1.0"
lazysort = "0.1"
semver = "0.6"
regex = "0.2"
clap = "2.22"
json = "0.11"
toml = "0.3"

[build-dependencies]
embed-resource = "1.1"


[[bin]]
name = "cargo-install-update"
test = false
doc = false
